In [83]:
import pandas as pd
import matplotlib

print("Todo listo")

Todo listo

# EDA

## ¿Qué tengo?

In [84]:
nobel = pd.read_csv("nobel_premio.csv")
nobel.head()

,laureateId,knownName,gender,birthDate,birthCountry,birthContinent,awardYear,category,portion,prizeAmount
0,1065,Henri B. Kagan,male,1930-12-15,France,Europe,2026,Chemistry,1/2,12000000
1,1066,Kenso Soai,male,1950-00-00,Japan,Asia,2026,Chemistry,1/2,12000000
2,1070,Michael Woodford,male,1955-00-00,USA,North America,2026,Economic Sciences,1/2,12000000
3,1069,Robert E. Hall,male,1943-00-00,USA,North America,2026,Economic Sciences,1/2,12000000
4,1067,Anne Carson,female,1950-06-21,Canada,North America,2026,Literature,1,12000000

In [85]:
nobel.columns = ["ID", "Nombre", "Genero", "FNac", "Pais", "Continente", "Año", "Categoria", "Porcion", "Monto"]
nobel.head()

,ID,Nombre,Genero,FNac,Pais,Continente,Año,Categoria,Porcion,Monto
0,1065,Henri B. Kagan,male,1930-12-15,France,Europe,2026,Chemistry,1/2,12000000
1,1066,Kenso Soai,male,1950-00-00,Japan,Asia,2026,Chemistry,1/2,12000000
2,1070,Michael Woodford,male,1955-00-00,USA,North America,2026,Economic Sciences,1/2,12000000
3,1069,Robert E. Hall,male,1943-00-00,USA,North America,2026,Economic Sciences,1/2,12000000
4,1067,Anne Carson,female,1950-06-21,Canada,North America,2026,Literature,1,12000000

In [86]:
print(nobel.shape)

(1036, 10)

In [87]:
nobel.info()

<class 'pandas.DataFrame'>
RangeIndex: 1036 entries, 0 to 1035
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1036 non-null   int64
 1   Nombre      1036 non-null   str
 2   Genero      1036 non-null   str
 3   FNac        1005 non-null   str
 4   Pais        1005 non-null   str
 5   Continente  1005 non-null   str
 6   Año         1036 non-null   int64
 7   Categoria   1036 non-null   str
 8   Porcion     1036 non-null   str
 9   Monto       1036 non-null   int64
dtypes: int64(3), str(7)
memory usage: 81.1 KB

## ¿Qué me falta?

In [88]:
nobel.isna().sum()

ID             0
Nombre         0
Genero         0
FNac          31
Pais          31
Continente    31
Año            0
Categoria      0
Porcion        0
Monto          0
dtype: int64

In [89]:
nobel[nobel.duplicated(subset=['ID'], keep=False)]

,ID,Nombre,Genero,FNac,Pais,Continente,Año,Categoria,Porcion,Monto
48,743,K. Barry Sharpless,male,1941-04-28,USA,North America,2022,Chemistry,1/3,10000000
302,743,K. Barry Sharpless,male,1941-04-28,USA,North America,2001,Chemistry,1/2,10000000
513,515,Office of the United Nations High Commissioner...,organization,NaN,NaN,NaN,1981,Peace,1,1000000
520,222,Frederick Sanger,male,1918-08-13,United Kingdom,Europe,1980,Chemistry,1/4,880000
615,66,John Bardeen,male,1908-05-23,USA,North America,1972,Physics,1/3,480000
686,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1963,Peace,1/2,265000
697,217,Linus Pauling,male,1901-02-28,USA,North America,1962,Peace,1,257220
721,222,Frederick Sanger,male,1918-08-13,United Kingdom,Europe,1958,Chemistry,1,214559
739,66,John Bardeen,male,1908-05-23,USA,North America,1956,Physics,1/3,200123
750,217,Linus Pauling,male,1901-02-28,USA,North America,1954,Chemistry,1,181647
752,515,Office of the United Nations High Commissioner...,organization,NaN,NaN,NaN,1954,Peace,1,181647
821,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1944,Peace,1,121841
947,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1917,Peace,1,133823
968,6,Marie Curie,female,1867-11-07,Poland,Europe,1911,Chemistry,1,140695
1020,6,Marie Curie,female,1867-11-07,Poland,Europe,1903,Physics,1/4,141358

In [90]:
nobel[nobel.eq("Unknown").any(axis=1)]

,ID,Nombre,Genero,FNac,Pais,Continente,Año,Categoria,Porcion,Monto
19,1052,John M. Martinis,male,1958-00-00,Unknown,Unknown,2025,Physics,1/3,11000000
28,1046,James A. Robinson,male,1960-00-00,Unknown,Unknown,2024,Economic Sciences,1/3,11000000
66,1004,Abdulrazak Gurnah,male,1948-00-00,Unknown,Unknown,2021,Literature,1,10000000

In [91]:
nobel[nobel.isnull().any(axis=1)] #Las filas que tiene "huecos", en realidad son organizaciones.

,ID,Nombre,Genero,FNac,Pais,Continente,Año,Categoria,Porcion,Monto
31,1043,Nihon Hidankyo,organization,NaN,NaN,NaN,2024,Peace,1,11000000
55,1020,Center for Civil Liberties,organization,NaN,NaN,NaN,2022,Peace,1/3,10000000
56,1019,Memorial,organization,NaN,NaN,NaN,2022,Peace,1/3,10000000
79,994,World Food Programme,organization,NaN,NaN,NaN,2020,Peace,1,10000000
118,948,International Campaign to Abolish Nuclear Weapons,organization,NaN,NaN,NaN,2017,Peace,1,9000000
141,925,National Dialogue Quartet,organization,NaN,NaN,NaN,2015,Peace,1,8000000
167,893,Organisation for the Prohibition of Chemical W...,organization,NaN,NaN,NaN,2013,Peace,1,8000000
178,881,European Union,organization,NaN,NaN,NaN,2012,Peace,1,8000000
238,818,Intergovernmental Panel on Climate Change,organization,NaN,NaN,NaN,2007,Peace,1/2,10000000
247,810,Grameen Bank,organization,NaN,NaN,NaN,2006,Peace,1/2,10000000
259,797,International Atomic Energy Agency,organization,NaN,NaN,NaN,2005,Peace,1/2,10000000
310,748,United Nations,organization,NaN,NaN,NaN,2001,Peace,1/2,10000000
333,568,Doctors Without Borders,organization,NaN,NaN,NaN,1999,Peace,1,7900000
355,564,International Campaign to Ban Landmines,organization,NaN,NaN,NaN,1997,Peace,1/2,7500000
380,561,Pugwash Conferences on Science and World Affairs,organization,NaN,NaN,NaN,1995,Peace,1/2,7200000
449,550,United Nations Peacekeeping Forces,organization,NaN,NaN,NaN,1988,Peace,1,2500000
480,547,International Physicians for the Prevention of...,organization,NaN,NaN,NaN,1985,Peace,1,1800000
513,515,Office of the United Nations High Commissioner...,organization,NaN,NaN,NaN,1981,Peace,1,1000000
557,537,Amnesty International,organization,NaN,NaN,NaN,1977,Peace,1,700000
640,527,International Labour Organization,organization,NaN,NaN,NaN,1969,Peace,1,375000
668,525,United Nations Children's Fund,organization,NaN,NaN,NaN,1965,Peace,1,282000
686,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1963,Peace,1/2,265000
687,523,League of Red Cross Societies,organization,NaN,NaN,NaN,1963,Peace,1/2,265000
752,515,Office of the United Nations High Commissioner...,organization,NaN,NaN,NaN,1954,Peace,1,181647
798,509,American Friends Service Committee,organization,NaN,NaN,NaN,1947,Peace,1/2,146115
799,508,Friends Service Council,organization,NaN,NaN,NaN,1947,Peace,1/2,146115
821,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1944,Peace,1,121841
836,503,Nansen International Office for Refugees,organization,NaN,NaN,NaN,1938,Peace,1,155077
947,482,International Committee of the Red Cross,organization,NaN,NaN,NaN,1917,Peace,1,133823
976,477,Permanent International Peace Bureau,organization,NaN,NaN,NaN,1910,Peace,1,140703
1013,467,Institute of International Law,organization,NaN,NaN,NaN,1904,Peace,1,140859

In [92]:
nobel['FNac'] = nobel['FNac'].fillna("0")
nobel[nobel.isnull().any(axis=1)]

,ID,Nombre,Genero,FNac,Pais,Continente,Año,Categoria,Porcion,Monto
31,1043,Nihon Hidankyo,organization,0,NaN,NaN,2024,Peace,1,11000000
55,1020,Center for Civil Liberties,organization,0,NaN,NaN,2022,Peace,1/3,10000000
56,1019,Memorial,organization,0,NaN,NaN,2022,Peace,1/3,10000000
79,994,World Food Programme,organization,0,NaN,NaN,2020,Peace,1,10000000
118,948,International Campaign to Abolish Nuclear Weapons,organization,0,NaN,NaN,2017,Peace,1,9000000
141,925,National Dialogue Quartet,organization,0,NaN,NaN,2015,Peace,1,8000000
167,893,Organisation for the Prohibition of Chemical W...,organization,0,NaN,NaN,2013,Peace,1,8000000
178,881,European Union,organization,0,NaN,NaN,2012,Peace,1,8000000
238,818,Intergovernmental Panel on Climate Change,organization,0,NaN,NaN,2007,Peace,1/2,10000000
247,810,Grameen Bank,organization,0,NaN,NaN,2006,Peace,1/2,10000000
259,797,International Atomic Energy Agency,organization,0,NaN,NaN,2005,Peace,1/2,10000000
310,748,United Nations,organization,0,NaN,NaN,2001,Peace,1/2,10000000
333,568,Doctors Without Borders,organization,0,NaN,NaN,1999,Peace,1,7900000
355,564,International Campaign to Ban Landmines,organization,0,NaN,NaN,1997,Peace,1/2,7500000
380,561,Pugwash Conferences on Science and World Affairs,organization,0,NaN,NaN,1995,Peace,1/2,7200000
449,550,United Nations Peacekeeping Forces,organization,0,NaN,NaN,1988,Peace,1,2500000
480,547,International Physicians for the Prevention of...,organization,0,NaN,NaN,1985,Peace,1,1800000
513,515,Office of the United Nations High Commissioner...,organization,0,NaN,NaN,1981,Peace,1,1000000
557,537,Amnesty International,organization,0,NaN,NaN,1977,Peace,1,700000
640,527,International Labour Organization,organization,0,NaN,NaN,1969,Peace,1,375000
668,525,United Nations Children's Fund,organization,0,NaN,NaN,1965,Peace,1,282000
686,482,International Committee of the Red Cross,organization,0,NaN,NaN,1963,Peace,1/2,265000
687,523,League of Red Cross Societies,organization,0,NaN,NaN,1963,Peace,1/2,265000
752,515,Office of the United Nations High Commissioner...,organization,0,NaN,NaN,1954,Peace,1,181647
798,509,American Friends Service Committee,organization,0,NaN,NaN,1947,Peace,1/2,146115
799,508,Friends Service Council,organization,0,NaN,NaN,1947,Peace,1/2,146115
821,482,International Committee of the Red Cross,organization,0,NaN,NaN,1944,Peace,1,121841
836,503,Nansen International Office for Refugees,organization,0,NaN,NaN,1938,Peace,1,155077
947,482,International Committee of the Red Cross,organization,0,NaN,NaN,1917,Peace,1,133823
976,477,Permanent International Peace Bureau,organization,0,NaN,NaN,1910,Peace,1,140703
1013,467,Institute of International Law,organization,0,NaN,NaN,1904,Peace,1,140859

In [93]:
nobel.loc[nobel['ID'] == 1043, ['Pais', 'Continente']] = ['Japan', 'Asia']
nobel.loc[nobel['ID'] == 1020, ['Pais', 'Continente']] = ['Ukraine', 'Europe']
nobel.loc[nobel['ID'] == 1019, ['Pais', 'Continente']] = ['Russia', 'Asia']
nobel.loc[nobel['ID'] == 994, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 948, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 925, ['Pais', 'Continente']] = ['Tunisia', 'Africa']
nobel.loc[nobel['ID'] == 893, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 881, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 818, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 810, ['Pais', 'Continente']] = ['Bangladesh', 'Asia']
nobel.loc[nobel['ID'] == 797, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 784, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 568, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 564, ['Pais', 'Continente']] = ['Switzerland', 'Europe']
nobel.loc[nobel['ID'] == 561, ['Pais', 'Continente']] = ['Canada', 'North America']
nobel.loc[nobel['ID'] == 550, ['Pais', 'Continente']] = ['Norway', 'Europe']
nobel.loc[nobel['ID'] == 547, ['Pais', 'Continente']] = ['United States', 'North America']
nobel.loc[nobel['ID'] == 515, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 537, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 527, ['Pais', 'Continente']] = ['Switzerland', 'Europe']
nobel.loc[nobel['ID'] == 525, ['Pais', 'Continente']] = ['United States', 'North America']
nobel.loc[nobel['ID'] == 482, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 523, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 515, ['Pais', 'Continente']] = ['Switzerland', 'Europe']
nobel.loc[nobel['ID'] == 509, ['Pais', 'Continente']] = ['United States', 'North America']
nobel.loc[nobel['ID'] == 508, ['Pais', 'Continente']] = ['United Kingdom', 'Europe']
nobel.loc[nobel['ID'] == 482, ['Pais', 'Continente']] = ['Internacional', 'Internacional']
nobel.loc[nobel['ID'] == 503, ['Pais', 'Continente']] = ['Switzerland', 'Europe']
nobel.loc[nobel['ID'] == 477, ['Pais', 'Continente']] = ['Switzerland', 'Europe']
nobel.loc[nobel['ID'] == 467, ['Pais', 'Continente']] = ['Belgium', 'Eurpe']
nobel.loc[nobel['ID'] == 1052, ['Pais', 'Continente']] = ['United States', 'North America']
nobel.loc[nobel['ID'] == 1046, ['Pais', 'Continente']] = ['United Kingdom', 'Europe']
nobel.loc[nobel['ID'] == 1004, ['Pais', 'Continente']] = ['Tanzania', 'Afriza']